import {esc,position,json,km} from './utils.js';
let geographyPromise;const project=(lon,lat)=>[(lon-137)*100,-(Math.log(Math.tan(Math.PI/4+lat*Math.PI/360))*180/Math.PI-37.4)*100];const path=p=>p.map((v,i)=>(i?'L':'M')+v.map(n=>n.toFixed(2)).join(',')).join('');
export async function renderMap(host,course,meters,onPoint){host.innerHTML='<p class="loading">海岸線と旅程を読み込んでいます…</p>';let geo;try{geo=await(geographyPromise??=json('data/geography.json'))}catch(e){geographyPromise=null;host.innerHTML='<p class="error">地理データを読み込めませんでした。接続を確認して、地図を開き直してください。</p>';return}if(!host.isConnected)return;
const points=course.points,sp=points.map(p=>project(p.lon,p.lat)),segments=sp.slice(0,-1).map((p,i)=>[p,...(points[i].via||[]).map(q=>project(...q)),sp[i+1]]),all=segments.flatMap((s,i)=>i?s.slice(1):s),pos=position(course,meters);let current=sp[pos.i],done=segments.slice(0,pos.i).flatMap((s,i)=>i?s.slice(1):s);
if(pos.b){const seg=segments[pos.i],len=seg.slice(1).map((q,i)=>Math.hypot(q[0]-seg[i][0],q[1]-seg[i][1]));let dist=pos.t*len.reduce((a,b)=>a+b,0);for(let j=0;j<len.length;j++){if(dist<=len[j]||j===len.length-1){const t=dist/len[j];current=seg[j].map((n,k)=>n+(seg[j+1][k]-n)*t);done.push(...seg.slice(0,j+1),current);break}dist-=len[j]}}else done=all;
const lands=geo.map(g=>g.rings.map(r=>path(r.map(p=>project(...p)))+'Z').join(''));let mode='detail',view,zoom=1,selection=pos.i;
host.innerHTML=`<div class="tabs"><button id="detail-mode" class="active">旅程を拡大</button><button id="japan-mode">日本全体</button></div><p class="map-help">指で上下左右に移動・2本指で拡大。地点をタップして読む。</p><div class="map-shell"><svg id="route-map" role="img" aria-label="海岸線・県境を含む日本地図と${esc(course.title)}の全旅程"></svg><div class="map-toolbar"><button id="zoom-in" aria-label="拡大">＋</button><button id="zoom-out" aria-label="縮小">−</button><button id="locate" aria-label="現在地へ">◎</button><button id="map-fit" aria-label="全旅程を表示">全</button></div></div><div class="map-legend"><span class="done">━ 踏破済み</span><span>┄ これから</span><span class="done">● 現在地</span></div><label class="form-label" for="map-select">全${points.length}地点から選ぶ</label><select id="map-select">${points.map((p,i)=>`<option value="${i}" ${i===selection?'selected':''}>${i+1}. ${esc(p.name)} ／ ${p.km.toFixed(1)}km</option>`).join('')}</select><div id="map-card"></div><p class="caption">背景：国土地理院「地球地図日本」／Data of Japanを加工。47都道府県の海岸線・県境を同梱。<a href="https://www.gsi.go.jp/kankyochiri/gm_jpn.html" target="_blank" rel="noopener">出典</a></p><div class="note">${esc(course.routeNote)}</div><details><summary>距離と地図の読み方</summary><p class="small">${esc(course.distanceNote)} 現在地は区間内の割合で補間した仮想位置。旧道のGPS案内には使えません。地図は北が上です。</p></details>`;
const $=s=>host.querySelector(s),svg=$('#route-map');function fit(){const aspect=svg.clientHeight/svg.clientWidth;const ps=mode==='japan'?[project(128,30),project(147,46)]:sp;const xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys);const w=Math.max(maxx-minx,(maxy-miny)/aspect)*1.22;view={x:(minx+maxx)/2,y:(miny+maxy)/2,w,h:w*aspect};zoom=1;draw()}
function scale(f,at){const nz=Math.max(1,Math.min(30,zoom*f)),ratio=nz/zoom;const q=at||[svg.clientWidth/2,svg.clientHeight/2],ax=view.x+(q[0]/svg.clientWidth-.5)*view.w,ay=view.y+(q[1]/svg.clientHeight-.5)*view.h;view={x:ax+(view.x-ax)/ratio,y:ay+(view.y-ay)/ratio,w:view.w/ratio,h:view.h/ratio};zoom=nz;draw()}
function focus(pt){mode='detail';syncTabs();fit();scale(4);view.x=pt[0];view.y=pt[1];draw()}
function syncTabs(){$('#detail-mode').classList.toggle('active',mode==='detail');$('#japan-mode').classList.toggle('active',mode==='japan')}
const labels=[['北海道',143,43.6],['東北',140.1,39.9],['関東',139.9,36.5],['中部',137.4,36.7],['近畿',135.1,35.4],['中国',132.6,34.9],['四国',133.5,33.4],['九州',130.7,32.5],['日本海',136.7,39.7],['太平洋',141.7,33.8],['東京',139.77,35.68],['京都',135.77,35.01],['大坂',135.5,34.69],['伊勢',136.71,34.47],['仙台',140.87,38.27],['金沢',136.65,36.56]];
function draw(){if(!svg.isConnected)return;const k=view.w/svg.clientWidth;svg.setAttribute('viewBox',`${view.x-view.w/2} ${view.y-view.h/2} ${view.w} ${view.h}`);svg.innerHTML=`<title>全${points.length}地点。現在：${esc(pos.a.name)}</title><g fill="#eee9d9" stroke="#9cac9b" stroke-width="${.6*k}" fill-rule="evenodd">${lands.map((d,i)=>`<path data-prefecture="${esc(geo[i].name)}" d="${d}"/>`).join('')}</g><g fill="#6a8079" font-size="${11*k}" text-anchor="middle" pointer-events="none">${labels.map(([n,lon,lat])=>{const p=project(lon,lat);return `<text x="${p[0]}" y="${p[1]}" stroke="#f5f2e6" stroke-width="${2*k}" paint-order="stroke">${n}</text>`}).join('')}</g><path d="${path(all)}" fill="none" stroke="#fff9eb" stroke-width="${7*k}"/><path class="route-future" d="${path(all)}" fill="none" stroke="#547277" stroke-width="${3*k}" stroke-dasharray="${5*k} ${3*k}"/><path class="route-done" d="${path(done)}" fill="none" stroke="#b55139" stroke-width="${4*k}"/><g class="station-markers">${points.map((p,i)=>{const [x,y]=sp[i],major=i===0||i===points.length-1||p.id==='hinaga',showLabel=major||mode==='detail'&&zoom>=5;return `<g class="map-point" data-point="${i}" tabindex="0" role="button" aria-label="${i+1}. ${esc(p.name)}" transform="translate(${x},${y})"><circle r="${11*k}" fill="transparent"/><circle r="${(major?4.5:2.8)*k}" fill="${p.km*1000<=meters?'#b55139':'#fff9ed'}" stroke="#264c4d" stroke-width="${k}"/>${showLabel?`<text x="${7*k}" y="${-8*k}" fill="#193f40" font-size="${11*k}" stroke="#fff9eb" stroke-width="${3*k}" paint-order="stroke">${esc(p.name)}</text>`:mode==='detail'&&zoom>=2?`<text y="${-7*k}" text-anchor="middle" font-size="${9*k}" fill="#193f40" stroke="#fff9eb" stroke-width="${2*k}" paint-order="stroke">${i+1}</text>`:''}</g>`}).join('')}</g><g class="current-position" data-lat="${pos.lat}" data-lon="${pos.lon}" transform="translate(${current})" pointer-events="none"><circle r="${13*k}" fill="#b5513930"/><circle r="${6*k}" fill="#b55139" stroke="white" stroke-width="${2*k}"/><rect x="${-24*k}" y="${-32*k}" width="${48*k}" height="${17*k}" rx="${4*k}" fill="#b55139"/><text text-anchor="middle" y="${-20*k}" font-size="${10*k}" fill="white">現在地</text></g>`}
function card(){const p=points[selection];$('#map-card').innerHTML=`<div class="note"><span class="eyebrow">${p.km*1000<=meters?'到達済み':'これから'}</span><h3>${esc(p.name)}</h3><p class="small">${esc(p.location)}<br>出発から約 ${p.km.toFixed(1)} km</p><button class="btn full" id="map-open">この地点をひらく</button></div>`;$('#map-open').onclick=()=>onPoint(p.id)}
$('#detail-mode').onclick=()=>{mode='detail';syncTabs();fit()};$('#japan-mode').onclick=()=>{mode='japan';syncTabs();fit()};$('#zoom-in').onclick=()=>scale(1.6);$('#zoom-out').onclick=()=>scale(1/1.6);$('#locate').onclick=()=>focus(current);$('#map-fit').onclick=fit;$('#map-select').onchange=e=>{selection=Number(e.target.value);focus(sp[selection]);card()};fit();card();
const pointers=new Map();let pressed=null,moved=false,start=null,lastDistance=null;const rel=e=>{const r=svg.getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top]};svg.addEventListener('pointerdown',e=>{pressed=e.target.closest('[data-point]')?.dataset.point??null;start=rel(e);pointers.set(e.pointerId,start);svg.setPointerCapture(e.pointerId);moved=false;lastDistance=null});svg.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId),p=rel(e);pointers.set(e.pointerId,p);if(pointers.size===1){if(Math.hypot(p[0]-start[0],p[1]-start[1])>5)moved=true;if(moved){view.x-=(p[0]-old[0])*view.w/svg.clientWidth;view.y-=(p[1]-old[1])*view.h/svg.clientHeight;draw()}}else{moved=true;const [a,b]=[...pointers.values()],d=Math.hypot(a[0]-b[0],a[1]-b[1]);if(lastDistance)scale(d/lastDistance,[(a[0]+b[0])/2,(a[1]+b[1])/2]);lastDistance=d}});svg.addEventListener('pointerup',e=>{if(!moved&&pressed!==null){selection=Number(pressed);$('#map-select').value=selection;card();onPoint(points[selection].id)}pointers.delete(e.pointerId);pressed=null;lastDistance=null});svg.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);pressed=null;lastDistance=null});svg.addEventListener('wheel',e=>{e.preventDefault();scale(e.deltaY<0?1.15:1/1.15,rel(e))},{passive:false});svg.addEventListener('keydown',e=>{const p=e.target.closest('[data-point]');if(p&&['Enter',' '].includes(e.key)){e.preventDefault();onPoint(points[Number(p.dataset.point)].id)}});
}